<template>
  <div class="suggestions-indicator" v-if="numberOfSuggestions > 0">
    {{ numberOfSuggestions }} {{ suggestionsText }}
  </div>
</template>

<style>

</style>

<script>
  export default {
    name: 'suggestions-indicator',
    props: {
      numberOfSuggestions: {
        type: Number,
        default: 0
      }
    },
    computed: {
      suggestionsText() {
        return this.numberOfSuggestions === 1 ? 'suggestion' : 'suggestions'
      }
    }
  }
</script>

<docs>

  Shows the number of suggestions generated by the system.

  ```jsx
  <suggestions-indicator number-of-suggestions="2"></suggestions-indicator>
  ```

</docs>
